# Add a custom overlay to the Gentoo Prefix installation.
---
- name: Add portage user if missing
  become: True
  lineinfile:
    path: /etc/passwd
    regexp: portage
    line: portage:x:250:250:portage:/var/tmp/portage:/bin/false

- name: Add portage group if missing
  become: True
  lineinfile:
    path: /etc/group
    regexp: portage
    line: portage::250:portage

- name: Install equery command (dependency for the portage module)
  command:
    cmd: emerge gentoolkit
    creates: "{{ gentoo_prefix_path }}/usr/bin/equery"

- name: Create repos directory
  file:
    path: "{{ gentoo_prefix_path }}/etc/portage/repos.conf"
    state: directory
    mode: '0755'

- name: Install eselect-repository
  portage:
    package: eselect-repository
    state: present

# We need git in order to add Gentoo overlays hosted on git repositories.
- name: Install git
  portage:
    package: dev-vcs/git
    state: present

- name: Check which repositories have been installed
  command: eselect repository list -i
  register: repositories_installed
  changed_when: False

- name: Add custom overlay configuration
  command:
    cmd: "eselect repository add {{ item.name }} {{ item.source }} {{ item.url }}"
  when: item.name not in repositories_installed.stdout
  loop: "{{ custom_overlays }}"

- name: Make configuration file with overlays that can override eclasses
  copy:
    dest: "{{ gentoo_prefix_path }}/etc/portage/repos.conf/eclass-overrides.conf"
    mode: "0644"
    content: |
      [DEFAULT]
      eclass-overrides = {{
        custom_overlays | selectattr('eclass-overrides', 'defined') |
        selectattr('eclass-overrides', 'equalto', True) | map(attribute='name') | join(' ')
      }}

- name: Use git instead of rsync for the Gentoo overlay
  copy:
    dest: "{{ gentoo_prefix_path }}/etc/portage/repos.conf/gentoo.conf"
    mode: "0644"
    content: |
      [DEFAULT]
      main-repo = gentoo
      sync-git-pull-extra-opts = --quiet

      [gentoo]
      priority  = 1
      location  = {{ gentoo_prefix_path }}/var/db/repos/gentoo
      sync-uri  = https://github.com/gentoo/gentoo.git
      sync-type = git
      auto-sync = Yes
      clone-depth = 1

- name: Create repo.postsync.d directory
  file:
    path: "{{ gentoo_prefix_path }}/etc/portage/repo.postsync.d"
    state: directory
    mode: '0755'

- name: Add post-sync hooks for Gentoo overlay
  copy:
    src: "{{ item }}"
    dest: "{{ gentoo_prefix_path }}/etc/portage/repo.postsync.d/{{ item }}"
    mode: 0755
  with_items:
    - sync_gentoo_cache
    - sync_gentoo_dtd
    - sync_gentoo_glsa
    - sync_gentoo_news
    - sync_overlay_cache

- name: Remove the old Gentoo overlay directory
  file:
    state: absent
    path: "{{ gentoo_prefix_path }}/var/db/repos/gentoo"

- name: Sync the repositories
  portage:
    sync: 'yes'

- name: Find all files and directories in the etc/portage directory of the overlay
  find:
    file_type: any
    paths: "{{ gentoo_prefix_path }}/var/db/repos/{{ item.name }}/etc/portage"
  loop: "{{ custom_overlays }}"
  register: find_configs

- name: Make symlinks to the portage settings in the custom overlay
  file:
    src: "{{ item.path }}"
    dest: "{{ gentoo_prefix_path }}/etc/portage/{{ item.path | basename }}"
    state: link
    force: yes
  with_items:
    "{{ find_configs.results | rejectattr('files', 'equalto', []) | map(attribute='files') | list }}"

- name: Update system set if we are running in an existing Prefix installation
  portage:
    changed_use: yes
    deep: yes
    package: "@system"
    update: yes
  when: startprefix.stat.exists
