# Replace a list of files/directories in Gentoo Prefix installation by symlinks to corresponding files/directories
# on the host in order to solve some common issues.
---

- name: Check type of original files/directories
  ansible.builtin.stat:
    path: "{{ gentoo_prefix_path }}{{ item }}"
  with_items: "{{ symlinks_to_host }}"
  register: orig_types

- name: Remove original files/directories
  ansible.builtin.file:
    path: "{{ gentoo_prefix_path }}{{ item.item }}"
    state: absent
  with_items: "{{ orig_types.results }}"
  when:
    - item.stat.exists
    - not item.stat.islnk

- name: Make symlinks
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ gentoo_prefix_path }}{{ item }}"
    state: link
    force: true
  with_items: "{{ symlinks_to_host }}"
