# Install a specified list of sets and packages.
---
- name: Install package set {{ package_sets }}
  community.general.portage:
    package: "@{{ item }}"
    state: present
  with_items: "{{ package_sets }}"
  tags:
    - set

- name: Install additional packages
  community.general.portage:
    package: "{{ item }}"
    state: present
  with_items: "{{ prefix_packages }}"

- name: "Get the username running the deployment (not root)"
  ansible.builtin.command: whoami
  changed_when: false
  register: username_on_host
