# Install a specified list of sets and packages.
---
- name: Install package set {{ package_sets }}
  community.general.portage:
    package: "@{{ item }}"
    state: present
  with_items: "{{ package_sets }}"
  vars:
    ansible_python_interpreter: "{{ gentoo_prefix_path }}/usr/bin/python3"
  tags:
    - set
#  ansible.builtin.command:
#    cmd: emerge --noreplace "@{{ item }}"
#  register: emerge_item_from_set
#  with_items: "{{ package_sets }}"
#  tags:
#    - set
#  changed_when: emerge_item_from_set.rc != 0

- name: Install additional packages
  community.general.portage:
    package: "{{ item }}"
    state: present
  with_items: "{{ prefix_packages }}"
  vars:
    ansible_python_interpreter: "{{ gentoo_prefix_path }}/usr/bin/python3"
#  ansible.builtin.command:
#    cmd: emerge "{{ item }}"
#  register: emerge_additional_item
#  with_items: "{{ prefix_packages }}"
#  when: prefix_packages is iterable
#  changed_when: emerge_additional_item.rc != 0
