# Install a specified list of sets and packages.
---
- name: Check if glibc has already been (re)installed with the user-defined-trusted-dirs option
  command: "grep {{ prefix_user_defined_trusted_dir }} {{ gentoo_prefix_path }}/usr/lib64/libc.a"
  register: glibc_reinstalled
  when: eessi_host_os == "linux"
  failed_when: glibc_reinstalled.rc >= 2

- name: Reinstall glibc with the user-defined-trusted-dirs option
  portage:
    package: sys-libs/glibc
    noreplace: no
    oneshot: yes
  become: no
  environment:
    EXTRA_EMAKE="user-defined-trusted-dirs={{ prefix_user_defined_trusted_dir }}"
  when: eessi_host_os == "linux" and glibc_reinstalled.rc != 0

- name: Install package set {{ package_sets }}
  portage:
    package: "@{{ item }}"
    state: present
  with_items: "{{ package_sets }}"
  become: no
  tags:
    - set

- name: Install additional packages
  portage:
    package: "{{ item }}"
    state: present
  with_items: "{{ prefix_packages }}"
  become: no

- name: "Get the username running the deployment (not root)"
  command: whoami
  changed_when: false
  become: no
  register: username_on_host

- name: "Fix permissions after installing as portage/root"
  file:
    owner: "{{ username_on_host.stdout }}"
    group: "{{ username_on_host.stdout }}"
    path: "{{ gentoo_prefix_path }}"
    recurse: true
  become: yes
