# Main task which:
# - checks the given path for a Prefix installation, and installs it if necessary;
# - starts (and publishes at the end) a CVMFS transaction, if requested;
# - calls the tasks for adding the overlay and installation of sets and packages;
# - does some fixes and other modifications in the Prefix installation (e.g. setting the locale).
---

- name: Check if a Prefix installation is found at the specified location
  stat:
    path: "{{ gentoo_prefix_path }}/startprefix"
  register: startprefix

- include_tasks: install_prefix.yml
  when: not startprefix.stat.exists

- name: Start transaction
  command: "cvmfs_server transaction {{ cvmfs_repository }}"
  when: cvmfs_start_transaction

- block:
  - include_tasks: prefix_configuration.yml

  - include_tasks: add_overlay.yml
    args:
      apply:
        become: False

  - include_tasks: set_glibc_trusted_dirs.yml

  - include_tasks: install_packages.yml

  - include_tasks: create_host_symlinks.yml

  - include_tasks: test.yml
    tags:
      - test

  - name: Publish transaction
    command: "cvmfs_server publish {{ cvmfs_repository }}"
    when: cvmfs_start_transaction and cvmfs_publish_transaction

  rescue:
    - name: Abort transaction
      command: "cvmfs_server abort {{ cvmfs_repository }}"
      when: cvmfs_start_transaction and cvmfs_abort_transaction_on_failures

    - name: Exit because of failure
      fail:
        msg: "Task {{ ansible_failed_task }} failed, with result {{ ansible_failed_result }}."
