# General configuration of the Prefix installation,
# for instance locale support.
---

- name: Add locales to configuration file
  lineinfile:
    path: "{{ gentoo_prefix_path }}/etc/locale.gen"
    line: "{{ item }}"
    state: present
  with_items: "{{ prefix_locales }}"
  notify: Generate locales

- name: Make the most recent GCC version the default
  command: "{{ gentoo_prefix_path }}/usr/bin/gcc-config latest"
  changed_when: false
