# Defaults file for the compatibility layer role.
---
eessi_version: "2020.11"

custom_overlay_name: eessi
custom_overlay_source: git
custom_overlay_url: https://github.com/EESSI/gentoo-overlay.git

cvmfs_start_transaction: False
cvmfs_publish_transaction: False
cvmfs_abort_transaction_on_failures: False
cvmfs_repository: pilot.eessi-hpc.org

gentoo_prefix_path: /cvmfs/{{ cvmfs_repository }}/{{ eessi_version }}/compat/{{ eessi_host_arch }}

# How to build the prefix
prefix_singularity_command: "singularity run -B {{ gentoo_prefix_path }}:{{ gentoo_prefix_path }}"
prefix_source: "docker://eessi/bootstrap-prefix:centos8-{{ eessi_host_arch }}"
prefix_source_options: "{{ gentoo_prefix_path }} noninteractive"
prefix_install: "SINGULARITYENV_USE_CPU_CORES={{ ansible_processor_vcpus }} {{ prefix_singularity_command }} {{ prefix_source }} {{ prefix_source_options }}"

# Logging
eessi_log_dir: "/tmp/eessi-logs"
prefix_build_log: "{{ eessi_log_dir }}/prefix-build.log"
emerge_log: "{{ gentoo_prefix_path }}/var/log/emerge.log"

prefix_locales:
  - en_US.UTF-8 UTF-8

package_sets: 
  - "{{ eessi_version }}"

prefix_packages:

# Set this to the same Python version as used during the Gentoo Prefix bootstrap.
# This ensures that no other Python version gets installed while adding the custom overlay. 
python_targets: "python3_7"

# List of locations that should get a symlink $EPREFIX/$LOCATION -> $LOCATION.
# This ensures that things like user/group ids are correct/looked up in the right way in the Prefix environment.
symlinks_to_host:
  # required to ensure local user groups are known
  - /etc/group 

  # required to ensure local users are known (see https://github.com/EESSI/compatibility-layer/issues/15)
  - /etc/passwd 

  # required to ensure name-service information is taken from the right source (e.g. ldap)
  - /etc/nsswitch.conf

  # required to use the DNS resolver from the host (should be done automatically)
  - /etc/resolv.conf

  # required if Centrify is used in nsswitch.conf
  - /lib64/libnss_centrifydc.so.2

  # required if LDAP is used in nsswitch.conf
  - /lib64/libnss_ldap.so.2

  # required if SSSD is used in nsswitch.conf
  - /lib64/libnss_sss.so.2

#  - /etc/hosts
#  - /var/lib/munge
#  - /var/lib/unbound
#  - /var/lib/VirtualGL
#  - /var/log/munge
#  - /var/log/wtmp
#  - /var/run
#  - /var/spool
#  - /var/tmp
#  - /run/dbus
#  - /tmp
