# Defaults file for the compatibility layer role.
---
eessi_version: "2023"

custom_overlays:
  - name: computecanada
    source: git
    url: https://github.com/ComputeCanada/gentoo-overlay.git
    eclass-overrides: true

cvmfs_repository: cmvfs.computecanada.ca

gentoo_prefix_path: /cvmfs/{{ cvmfs_repository }}/gentoo/{{ eessi_version }}

# How to build the prefix.
gentoo_git_repo: https://github.com/gentoo/gentoo.git
# Select a specific commit in the gentoo_git_repo that should be used for the bootstrap,
# e.g. by checking: https://github.com/gentoo/gentoo/commits/master
# April 17 (29492845e41ea6a0a4a9769c7e0ce287d106079b) commit is after fix for Lmod
# gentoo_git_commit: 29492845e41ea6a0a4a9769c7e0ce287d106079b
# June 8 (aab8473aa90e0287553b3348a5c5b17872df4b7b) commit that was current when fetching luaposix
gentoo_git_commit: aab8473aa90e0287553b3348a5c5b17872df4b7b
prefix_required_space: 15 GB
prefix_user_defined_trusted_dirs:
  - "/cvmfs/{{ cvmfs_repository }}/host_injections/{{ eessi_version }}/lib"
prefix_mask_packages: |
  # to allow eb --new-pr via X forwarding
  >=dev-python/secretstorage-3
prefix_bootstrap_use_flags: |
  # only install Python 3.11
  */* PYTHON_TARGETS: -* python3_11
  */* PYTHON_SINGLE_TARGET: -* python3_11
prefix_use_builtin_bootstrap: false
prefix_custom_bootstrap_script:
  local: "{{ playbook_dir }}/../../bootstrap-prefix-upstream.sh"
  remote: /tmp/bootstrap-prefix.sh
prefix_source_options: "{{ gentoo_prefix_path }} noninteractive"
prefix_install: >-
    {{ prefix_use_builtin_bootstrap | ternary('/usr/local/bin/bootstrap-prefix.sh', prefix_custom_bootstrap_script.remote) }}
    {{ prefix_source_options }}

# Reproducibility settings
prefix_reprod_dir: reprod
prefix_packages_file: packages.txt
prefix_metadata_json: build.json

# Logging
eessi_log_dir: "/tmp/eessi-logs"
prefix_build_log: "{{ eessi_log_dir }}/prefix-build.log"
emerge_log: "{{ gentoo_prefix_path }}/var/log/emerge.log"

prefix_locales:
  - en_US.UTF-8 UTF-8
  - en_CA.UTF-8 UTF-8
  - fr_CA.UTF-8 UTF-8
  - en_GB.UTF-8 UTF-8

# By default, we install an architecture-specific set
package_sets:
  - "computecanada-{{ eessi_version }}"

prefix_packages:

prefix_remove_packages:
  - app-eselect/eselect-rust
  - dev-lang/go
  - dev-lang/go-bootstrap
  - dev-lang/rust
  - dev-lang/rust-bin
  - dev-python/setuptools-rust
  - dev-util/cmake
  - dev-util/ninja
  - virtual/rust

reframe_venv_dir: /tmp/reframe_venv

# List of locations that should get a symlink $EPREFIX/$LOCATION -> $LOCATION.
# This ensures that things like user/group ids are correct/looked up in the right way in the Prefix environment.
symlinks_to_host:
  # required to ensure name-service information is taken from the right source (e.g. ldap)
  - /etc/nsswitch.conf

  # required to pick up the right timezone from the host
  - /etc/localtime

#  - /var/lib/munge
#  - /var/lib/unbound
#  - /var/lib/VirtualGL
#  - /var/log/munge
#  - /var/log/wtmp
#  - /var/run
#  - /var/spool
#  - /var/tmp
#  - /run/dbus
#  - /tmp
