# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Tests for EESSI pilot repo
on: [push, pull_request]
jobs:
  pilot_repo:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        EESSI_VERSION:
        # note: use string quotes here, to avoid values being interpreted as floating point values...
        - '2020.12'
        - '2021.02'
        EESSI_ARCH:
        - aarch64
        - ppc64le
        - x86_64
        python:
        - 3.8
    steps:
        - name: Install QEMU
          if: matrix.EESSI_ARCH != 'x86_64'
          run: |
              sudo apt-get update
              sudo apt-get install qemu-user

        - name: Mount EESSI CernVM-FS pilot repository
          uses: cvmfs-contrib/github-action-cvmfs@main
          with:
              cvmfs_config_package: https://github.com/EESSI/filesystem-layer/releases/download/v0.2.3/cvmfs-config-eessi_0.2.3_all.deb
              cvmfs_http_proxy: DIRECT
              cvmfs_repositories: pilot.eessi-hpc.org

        - name: Check compat layer in EESSI pilot repository
          env:
              EPREFIX: /cvmfs/pilot.eessi-hpc.org/${{matrix.EESSI_VERSION}}/compat/linux/${{matrix.EESSI_ARCH}}
          run: |
              # trigger automount
              echo '>> ls /cvmfs/pilot.eessi-hpc.org'
              ls /cvmfs/pilot.eessi-hpc.org

              # check which Stratum 1 we're connected to
              echo '>> cvmfs_config stat -v pilot.eessi-hpc.org'
              cvmfs_config stat -v pilot.eessi-hpc.org

              echo '>> ls ${EPREFIX}/startprefix'
              ls ${EPREFIX}/startprefix

              # enter Prefix environment, list installed packages, and exit
              # this magically works, even for non-x86_64 architectures, thanks to QEMU \o/
              echo '>> ${EPREFIX}/startprefix <<< "which bash; qlist -IRv; exit"'
              ${EPREFIX}/startprefix <<< "which bash; qlist -IRv; exit"

#        - name: set up Python
#          uses: actions/setup-python@v1
#          with:
#            python-version: ${{matrix.python}}
#            architecture: x64

#        - name: install Python packages
#          run: |
#            pip install pytest

#        - name: Setup BATS
#          uses: mig4/setup-bats@v1
#          with:
#            bats-version: 1.2.1

        - name: Check out code
          uses: actions/checkout@v2

        - name: GitHub Action for pytest
          uses: cclauss/GitHub-Action-for-pytest@master
          with:
            args: pytest --eessi-version=${{matrix.EESSI_VERSION}} --eessi-arch=${{matrix.EESSI_ARCH}} ./test


#        - name: Run BATS test suite
#          env:
#              EESSI_COMPAT_DIR: /cvmfs/pilot.eessi-hpc.org/${{matrix.EESSI_VERSION}}/compat/linux/${{matrix.EESSI_ARCH}}
#          run: bats -r ${{github.workspace}}/test/
